// Phase 1 local renderer for Sing My Birthday short-form videos (v2 — polish pass).
//
// Pipeline (no external APIs, no publishing, no spend):
//   posts.json → guardrails → layered SVG overlays (sharp) + drifting brand
//   gradient (ffmpeg) → staged fade-in reveals → 1080x1920 MP4
//   → per-platform .txt captions + .json metadata.
//
// v2 quality: Avenir Next typography + highlighted keyword, eyebrow kicker,
// procedural confetti/music-note/sparkle layer, edge vignette, platform-safe
// margins, background drift + parallax confetti, and staged reveals for pacing.
//
// Compliance guardrails live in lib.mjs and are UNCHANGED by this file.
// Run: `npm run content:render` | `node ... --only=smb_wk1_d4` | `... --dry`

import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import sharp from "sharp";
import {
  loadCalendar, evaluateGuardrails, schemaErrors, ensureDir,
  ROOT, OUTPUT_DIR, ASSETS_DIR, LOGO, SITE_HOST, GRADIENTS, DEFAULT_GRADIENT,
  stripEmoji, escapeXml, wrapText, cleanCtaForVideo, buildPlatformCaption, nowIso,
} from "./lib.mjs";

const W = 1080;
const H = 1920;
const DURATION = 10;
const FPS = 30;
const FFMPEG = process.env.FFMPEG_PATH || "ffmpeg";

// Platform-safe margins (TikTok/IG keep the bottom ~20% + right rail busy).
const SIDE = 96;
const SAFE_TOP = 150;
const SAFE_BOTTOM_Y = 1540; // nothing meaningful below this line

const FONT = "Avenir Next, Helvetica Neue, Arial, sans-serif";
const GOLD = "#FDE68A";
const PINK = "#F9A8D4";

const PILLAR_KICKER = {
  how_it_works: "HOW IT WORKS",
  use_case: "THE PERFECT GIFT",
  reveal: "PRESS PLAY",
  relatable: "GIFT INSPO",
  winner_repost: "FAN FAVORITE",
  test: "NEW",
};
const HIGHLIGHT_WORDS = [
  "song", "songs", "name", "gift", "birthday", "yours", "your", "their",
  "love", "vibe", "genre", "party", "moment", "custom", "person", "partner", "mom",
];

// Brand-safe audio bed (generated by make-audio-bed.mjs). Optional + configurable.
const AUDIO_BED = path.join(ASSETS_DIR, "audio", "brand-bed.m4a");
const BED_VOL = 0.22; // mix the bed subtly under the (otherwise silent) video

const argv = process.argv.slice(2);
const onlyArg = argv.find((a) => a.startsWith("--only="));
const ONLY = onlyArg ? onlyArg.split("=")[1] : null;
const DRY = argv.includes("--dry");
const SILENT = argv.includes("--silent");
const audioArg = argv.find((a) => a.startsWith("--audio="));
const AUDIO_OVERRIDE = audioArg ? audioArg.split("=")[1] : null;
const AUDIO_FILE = AUDIO_OVERRIDE || AUDIO_BED;
const AUDIO_MODE = SILENT
  ? "silent"
  : fs.existsSync(AUDIO_FILE) ? path.basename(AUDIO_FILE) : "silent (no bed found)";

// Tiny seeded PRNG so confetti is varied per-post but reproducible.
function seedFrom(str) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
  return h >>> 0;
}
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const svgDoc = (inner) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H + 200}" viewBox="0 0 ${W} ${H + 200}">${inner}</svg>`;

// ── Layer 1: confetti / notes / sparkles (parallax, drifts upward) ──────────
function confettiSvg(post) {
  const rnd = mulberry32(seedFrom(post.post_id));
  const colors = ["#FFFFFF", GOLD, PINK, "#C4B5FD", "#A7F3D0"];
  const glyphs = ["♪", "♫", "✦", "✺", "●", "♥"];
  const parts = [];
  for (let i = 0; i < 46; i++) {
    const x = Math.round(rnd() * W);
    const y = Math.round(rnd() * (H + 180));
    const c = colors[Math.floor(rnd() * colors.length)];
    // Bias opacity down inside the central text band so type stays crisp.
    const central = y > 560 && y < 1120;
    const op = (central ? 0.1 : 0.22) + rnd() * 0.28;
    const rot = Math.round(rnd() * 60 - 30);
    if (rnd() < 0.45) {
      const r = 4 + Math.round(rnd() * 9);
      parts.push(`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" opacity="${op.toFixed(2)}"/>`);
    } else {
      const g = glyphs[Math.floor(rnd() * glyphs.length)];
      const fs = 20 + Math.round(rnd() * 30);
      parts.push(`<text x="${x}" y="${y}" font-family="${FONT}" font-size="${fs}" fill="${c}" opacity="${op.toFixed(2)}" transform="rotate(${rot} ${x} ${y})">${g}</text>`);
    }
  }
  return svgDoc(parts.join(""));
}

// ── Layer 2: base (vignette + scrims + kicker). Logo composited after. ──────
function baseSvg(post) {
  const kicker = PILLAR_KICKER[post.pillar] || "SING MY BIRTHDAY";
  return svgDoc(`
    <defs>
      <radialGradient id="vig" cx="50%" cy="42%" r="75%">
        <stop offset="55%" stop-color="#000000" stop-opacity="0"/>
        <stop offset="100%" stop-color="#000000" stop-opacity="0.42"/>
      </radialGradient>
      <linearGradient id="top" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="#000" stop-opacity="0.38"/><stop offset="1" stop-color="#000" stop-opacity="0"/>
      </linearGradient>
      <linearGradient id="bot" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity="0.5"/>
      </linearGradient>
    </defs>
    <rect x="0" y="0" width="${W}" height="${H}" fill="url(#vig)"/>
    <rect x="0" y="0" width="${W}" height="440" fill="url(#top)"/>
    <rect x="0" y="${H - 520}" width="${W}" height="520" fill="url(#bot)"/>
    <text x="${W / 2}" y="382" font-family="${FONT}" font-weight="700" font-size="32"
          letter-spacing="8" fill="${GOLD}" text-anchor="middle" opacity="0.95">${escapeXml(kicker)}</text>
  `);
}

function hookSvg(post) {
  const lines = wrapText(stripEmoji(post.hook), 15, 3);
  const fs = 92, lh = 108, startY = 600;
  let highlighted = false;
  const norm = (w) => w.toLowerCase().replace(/[^a-z]/g, "");
  const lineSvg = lines.map((line, i) => {
    const y = startY + i * lh;
    const words = line.split(" ").map((w) => {
      if (!highlighted && HIGHLIGHT_WORDS.includes(norm(w))) {
        highlighted = true;
        return `<tspan fill="${PINK}">${escapeXml(w)}</tspan>`;
      }
      return escapeXml(w);
    }).join(" ");
    return `<text x="${W / 2}" y="${y}" font-family="${FONT}" font-weight="900" font-size="${fs}" fill="#FFFFFF" text-anchor="middle" filter="url(#sh)">${words}</text>`;
  }).join("");
  const supportTop = startY + lines.length * lh + 70;
  return { svg: svgDoc(`<defs><filter id="sh" x="-15%" y="-15%" width="130%" height="130%"><feDropShadow dx="0" dy="3" stdDeviation="8" flood-color="#000" flood-opacity="0.5"/></filter></defs>${lineSvg}`), supportTop };
}

function supportSvg(post, supportTop) {
  const lines = wrapText(stripEmoji(post.on_screen_text), 26, 2);
  const fs = 52, lh = 64;
  const t = lines.map((l, i) =>
    `<tspan x="${W / 2}" y="${supportTop + i * lh}">${escapeXml(l)}</tspan>`).join("");
  return svgDoc(`<defs><filter id="sh2" x="-15%" y="-15%" width="130%" height="130%"><feDropShadow dx="0" dy="2" stdDeviation="6" flood-color="#000" flood-opacity="0.45"/></filter></defs>
    <text font-family="${FONT}" font-weight="600" font-size="${fs}" fill="${GOLD}" text-anchor="middle" filter="url(#sh2)">${t}</text>`);
}

function ctaSvg(post) {
  const cta = cleanCtaForVideo(post.cta);
  const fs = 46;
  const pillW = Math.min(W - 2 * SIDE, Math.max(440, cta.length * 25 + 150));
  const pillX = (W - pillW) / 2;
  const pillY = 1300;
  return svgDoc(`
    <defs>
      <linearGradient id="pill" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0" stop-color="#A855F7"/><stop offset="0.5" stop-color="#EC4899"/><stop offset="1" stop-color="#F472B6"/>
      </linearGradient>
      <filter id="pillsh" x="-20%" y="-40%" width="140%" height="200%"><feDropShadow dx="0" dy="6" stdDeviation="14" flood-color="#000" flood-opacity="0.4"/></filter>
    </defs>
    <rect x="${pillX}" y="${pillY}" width="${pillW}" height="118" rx="59" fill="url(#pill)" filter="url(#pillsh)"/>
    <text x="${W / 2}" y="${pillY + 76}" font-family="${FONT}" font-weight="800" font-size="${fs}" fill="#FFFFFF" text-anchor="middle">${escapeXml(cta)}  →</text>
    <text x="${W / 2}" y="${pillY + 206}" font-family="${FONT}" font-weight="700" font-size="40" fill="#FFFFFF" text-anchor="middle" opacity="0.96" letter-spacing="1">${SITE_HOST}</text>
  `);
}

async function svgToPng(svg, outPath, withLogo = false) {
  let img = sharp(Buffer.from(svg));
  if (withLogo && fs.existsSync(LOGO)) {
    const logo = await sharp(LOGO).resize(132, 132, { fit: "inside" }).png().toBuffer();
    img = img.composite([{ input: logo, top: SAFE_TOP, left: Math.round((W - 132) / 2) }]);
  }
  await img.png().toFile(outPath);
}

async function buildLayers(post, dir) {
  const L = {
    confetti: path.join(dir, "_l_confetti.png"),
    base: path.join(dir, "_l_base.png"),
    hook: path.join(dir, "_l_hook.png"),
    support: path.join(dir, "_l_support.png"),
    cta: path.join(dir, "_l_cta.png"),
  };
  const hook = hookSvg(post);
  await svgToPng(confettiSvg(post), L.confetti);
  await svgToPng(baseSvg(post), L.base, true);
  await svgToPng(hook.svg, L.hook);
  await svgToPng(supportSvg(post, hook.supportTop), L.support);
  await svgToPng(ctaSvg(post), L.cta);
  return L;
}

function cleanupLayers(L) {
  for (const p of Object.values(L)) fs.rmSync(p, { force: true });
}

function resolveBackground(post) {
  // 1) explicit AI clip path (absolute, or relative to content-automation/).
  //    Only APPROVED clips should ever be referenced here (see AI-VIDEO-PILOT.md).
  if (post.source_ai_clip_path) {
    const p = path.isAbsolute(post.source_ai_clip_path)
      ? post.source_ai_clip_path
      : path.resolve(ROOT, post.source_ai_clip_path);
    if (fs.existsSync(p)) return { type: "clip", path: p };
  }
  // 2) approved AI clip by asset_id
  const aiClip = path.join(ASSETS_DIR, "ai-generated", "approved", `${post.asset_id}.mp4`);
  if (fs.existsSync(aiClip)) return { type: "clip", path: aiClip };
  // 3) cleared local clip by asset_id
  const localClip = path.join(ASSETS_DIR, `${post.asset_id}.mp4`);
  if (fs.existsSync(localClip)) return { type: "clip", path: localClip };
  // 4) brand gradient fallback (filler)
  const grad = GRADIENTS[post.asset_id] || GRADIENTS[DEFAULT_GRADIENT];
  return { type: "gradient", ...grad };
}

// Larger-than-frame bg → drift-crop yields organic motion (no static slide).
const GW = 1188, GH = 2112;

function ffmpegArgs(post, L, outMp4) {
  const bg = resolveBackground(post);
  const fadeOut = (DURATION - 0.6).toFixed(2);
  const inputs = [];
  let bgChain;
  if (bg.type === "clip") {
    inputs.push("-stream_loop", "-1", "-t", String(DURATION), "-i", bg.path);
    bgChain = `[0:v]scale=${GW}:${GH}:force_original_aspect_ratio=increase,crop=${GW}:${GH}`;
  } else {
    inputs.push("-f", "lavfi", "-i",
      `gradients=s=${GW}x${GH}:c0=${bg.c0}:c1=${bg.c1}:x0=0:y0=0:x1=${GW}:y1=${GH}:d=${DURATION}:speed=0.006`);
    bgChain = `[0:v]null`;
  }
  // Each overlay PNG must loop across the whole clip — a plain `-i image.png` is
  // a single frame at t=0, which makes time-based `fade`/`overlay` expressions
  // no-op. `-loop 1 -t DURATION` turns each into a continuous stream.
  for (const img of [L.confetti, L.base, L.hook, L.support, L.cta]) {
    inputs.push("-loop", "1", "-t", String(DURATION), "-i", img);
  }
  // Audio (input index 6): brand-safe bed by default, silent track on --silent.
  const bedPath = AUDIO_OVERRIDE || AUDIO_BED;
  const useBed = !SILENT && fs.existsSync(bedPath);
  if (useBed) {
    inputs.push("-stream_loop", "-1", "-t", String(DURATION), "-i", bedPath);
  } else {
    inputs.push("-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=44100");
  }

  // Drift-crop the bg to 1080x1920; parallax confetti drifts up; staged fades.
  let filter =
    `${bgChain},crop=${W}:${H}:x='54+sin(t/2.6)*22':y='96+cos(t/2.1)*22',format=rgba[bg];` +
    `[1:v]format=rgba[cf];` +
    `[bg][cf]overlay=x=0:y='-(t*9)':format=auto[b1];` +
    `[2:v]format=rgba,fade=t=in:st=0.0:d=0.6:alpha=1[base];` +
    `[3:v]format=rgba,fade=t=in:st=0.7:d=0.6:alpha=1[hk];` +
    `[4:v]format=rgba,fade=t=in:st=1.5:d=0.6:alpha=1[sp];` +
    `[5:v]format=rgba,fade=t=in:st=2.5:d=0.6:alpha=1[ct];` +
    `[b1][base]overlay=0:0[c1];` +
    `[c1][hk]overlay=0:0[c2];` +
    `[c2][sp]overlay=0:0[c3];` +
    `[c3][ct]overlay=0:0,fade=t=in:st=0:d=0.4,fade=t=out:st=${fadeOut}:d=0.6,format=yuv420p[v]`;

  let aMap = "6:a";
  if (useBed) {
    filter +=
      `;[6:a]volume=${BED_VOL},afade=t=in:st=0:d=0.3,afade=t=out:st=${fadeOut}:d=0.8,` +
      `aformat=sample_rates=44100:channel_layouts=stereo[a]`;
    aMap = "[a]";
  }

  return [
    "-y", ...inputs,
    "-filter_complex", filter,
    "-map", "[v]", "-map", aMap,
    "-t", String(DURATION), "-r", String(FPS),
    "-c:v", "libx264", "-profile:v", "high", "-preset", "veryfast", "-crf", "20",
    "-pix_fmt", "yuv420p", "-movflags", "+faststart",
    "-c:a", "aac", "-b:a", "128k", "-shortest",
    outMp4,
  ];
}

async function renderPost(post) {
  const dir = path.join(OUTPUT_DIR, post.post_id);
  ensureDir(dir);
  ensureDir(path.join(dir, "captions"));
  ensureDir(path.join(dir, "meta"));

  const L = await buildLayers(post, dir);
  const outMp4 = path.join(dir, `${post.post_id}.mp4`);
  const args = ffmpegArgs(post, L, outMp4);

  if (DRY) {
    cleanupLayers(L);
    console.log(`    [dry] ffmpeg ${args.length} args`);
    return { mp4: outMp4, captions: [], dry: true };
  }

  const res = spawnSync(FFMPEG, args, { encoding: "utf8" });
  cleanupLayers(L);
  if (res.status !== 0) {
    throw new Error(`ffmpeg failed (${res.status}): ${(res.stderr || "").split("\n").slice(-5).join(" ")}`);
  }

  const captionFiles = [];
  for (const platform of post.platforms) {
    const capPath = path.join(dir, "captions", `${post.post_id}.${platform}.txt`);
    const caption = buildPlatformCaption(post, platform);
    fs.writeFileSync(capPath, caption, "utf8");
    captionFiles.push(capPath);

    const metaPath = path.join(dir, "meta", `${post.post_id}.${platform}.json`);
    fs.writeFileSync(metaPath, JSON.stringify({
      post_id: post.post_id, campaign: post.campaign, date: post.date, pillar: post.pillar,
      platform, video: path.relative(OUTPUT_DIR, outMp4), caption_file: path.relative(OUTPUT_DIR, capPath),
      caption_text: caption, cta: post.cta, hashtags: post.hashtags, utm_url: post.utm_urls[platform],
      asset_id: post.asset_id, asset_type: post.asset_type, asset_permission_status: post.asset_permission_status,
      adult_targeting_confirmed: post.adult_targeting_confirmed,
      approval_status: post.approval_status, render_status: "rendered",
      channel_type: "organic", auto_post: false,
      ai_tool: post.ai_tool || null, ai_quality_status: post.ai_quality_status || null,
      source_ai_clip_path: post.source_ai_clip_path || null,
      audio: AUDIO_MODE, audio_volume: SILENT ? 0 : BED_VOL, generated_at: nowIso(),
    }, null, 2), "utf8");
  }
  return { mp4: outMp4, captions: captionFiles };
}

async function main() {
  ensureDir(OUTPUT_DIR);
  const data = loadCalendar();
  let posts = data.posts;
  if (ONLY) posts = posts.filter((p) => p.post_id === ONLY);
  if (posts.length === 0) {
    console.error(`No posts matched${ONLY ? ` --only=${ONLY}` : ""}.`);
    process.exit(1);
  }

  const report = [];
  console.log(`\n=== Sing My Birthday — Phase 1 render v2 (no posting) ===`);
  console.log(`audio: ${AUDIO_MODE}${SILENT ? "" : ` @ vol ${BED_VOL}`}\n`);

  for (const post of posts) {
    const errs = schemaErrors(post);
    const g = evaluateGuardrails(post);
    for (const w of g.warnings) console.log(`  ⚠ ${post.post_id}: ${w}`);

    if (errs.length) {
      console.log(`  ⛔ ${post.post_id}: SCHEMA-ERROR — ${errs.join("; ")}`);
      report.push({ post_id: post.post_id, render_status: "failed", reasons: errs });
      continue;
    }
    if (!g.eligible) {
      console.log(`  ⛔ ${post.post_id}: BLOCKED — ${g.reasons.join("; ")}`);
      report.push({ post_id: post.post_id, render_status: "blocked", reasons: g.reasons });
      continue;
    }
    try {
      const out = await renderPost(post);
      console.log(`  ✅ ${post.post_id}: ${out.dry ? "DRY (no file)" : "rendered → " + path.relative(OUTPUT_DIR, out.mp4)}`);
      report.push({
        post_id: post.post_id, render_status: out.dry ? "dry" : "rendered",
        video: out.dry ? null : path.relative(OUTPUT_DIR, out.mp4),
        platforms: post.platforms, approval_status: post.approval_status, auto_post: false,
      });
    } catch (e) {
      console.log(`  ✖ ${post.post_id}: FAILED — ${e.message}`);
      report.push({ post_id: post.post_id, render_status: "failed", reasons: [e.message] });
    }
  }

  const rendered = report.filter((r) => r.render_status === "rendered").length;
  const blocked = report.filter((r) => r.render_status === "blocked").length;
  const failed = report.filter((r) => r.render_status === "failed").length;

  if (!DRY) {
    fs.writeFileSync(
      path.join(OUTPUT_DIR, "_render-report.json"),
      JSON.stringify({ generated_at: nowIso(), rendered, blocked, failed, posts: report }, null, 2),
      "utf8",
    );
  }
  console.log(`\n--- summary ---`);
  console.log(`rendered: ${rendered}  |  blocked: ${blocked}  |  failed: ${failed}`);
  console.log(`output dir: ${OUTPUT_DIR}`);
  console.log(`\nNOTHING was posted. Review videos, then mark approval_status=approved for Phase 2.\n`);
  if (failed > 0) process.exit(1);
}

main().catch((e) => { console.error("render-posts fatal:", e); process.exit(1); });
